# See the syntax for the text in the readme.

# The text to display when a player enters a zone.
entered-zone-text: "entering"
# The text to display when a player is in no zone.
no-zone-text: "entering wilderness"
# The text to display when a player executes the who command.
who-text: "player(s) online:"
# Do you want who disabled?
no-who: false
# Will the zone left be displayed when leaving a zone.
no-zone-name: false
# Will only ops be able to use /mark.
ops-only-mark: false
# Will only ops be able to use /unmark.
ops-only-unmark: false
# Radius limit.
radius-limit: 1000
# The default radius if the user does not specify one.
radius-default: 25

# Debug the plugin?
debug: false
#    private String whoHead	       = "§e$1 player(s) online:";
#private String whoLinePlace    = "§e+ §f$1 §e- §f$2";
#    private String whoLineNoPlace  = "§e+ §f$1 §e- §fwilderness";
